"""اختبار الصانع (الواجهة الجديدة)، لوحة الإدارة، ولوحة المالك من البداية للنهاية على خادم وهمي."""
import asyncio

from harness import ADMIN, MAKER, MID, Check, boot, tok

B1 = 200000201


async def main():  # noqa: C901
    tg, mgr = await boot()
    ck = Check()
    ali, sara, omar = tg.user(500, "Ali"), tg.user(600, "Sara", username="sara_s"), tg.user(700, "Omar")
    boss = tg.user(ADMIN, "Boss")

    def outs(bot=MID):
        return [c["p"].get("text", "") for c in tg.out(bot)]

    print("— الصانع: الواجهة —")
    t = await tg.say(MAKER, ali, "/start")
    ck.ok("أهلاً Ali" in t and "①" in t, "رسالة البداية للمستخدم الجديد")
    ck.ok(tg.find(MID, "ابنِ بوتاً جديداً").get("style") == "success", "زر البناء ملوّن")
    ck.ok(not any("لوحة الإدارة" in b["text"] for b in tg.buttons(MID)), "زر الإدارة مخفي عن المستخدم العادي")
    t = await tg.press(MAKER, ali, "ابنِ بوتاً جديداً")
    ck.ok("الخطوة 1 من 3" in t and tg.find(MID, "تجارة وخدمات"), "الخطوة 1: المجالات")
    t = await tg.press(MAKER, ali, "تجارة وخدمات")
    ck.ok("متجر مصغر" in t and "منيو QR" in t and tg.find(MID, "حجز مواعيد"), "صفحة المجال تشرح كل نوع")
    t = await tg.click(MAKER, ali, "m:cat:hot")
    ck.ok("الأكثر استخداماً" in t, "الأكثر استخداماً")
    t = await tg.click(MAKER, ali, "m:all:0")
    ck.ok("34" in t, "كل الأنواع = 34")
    await tg.click(MAKER, ali, "m:tsearch")
    t = await tg.say(MAKER, ali, "حجز")
    ck.ok("حجز مواعيد" in t, "البحث في الأنواع")
    t = await tg.click(MAKER, ali, "m:tpl:decor")
    ck.ok("الخطوة 2 من 3" in t and "✓" in t and "BotFather" in t, "بطاقة النوع بالمزايا")
    t = await tg.press(MAKER, ali, "أول مرة")
    ck.ok("/newbot" in t and "_bot" in t, "شرح أول مرة")
    ck.ok("أنتظر التوكن" in await tg.say(MAKER, ali, "كلام عادي"), "ينتظر التوكن")
    tg.invalid.add("999000999:" + "C" * 35)
    ck.ok("غير صحيح" in await tg.say(MAKER, ali, "999000999:" + "C" * 35), "رفض توكن خاطئ")
    tg.webhooks[B1] = "https://other-maker.example/hook/abc"
    await tg.say(MAKER, ali, tok(B1))
    done = next((x for x in outs()[::-1] if "بوتك أصبح حياً" in x), "")
    ck.ok(bool(done) and mgr.running(B1), "الخطوة 3: إنشاء وتشغيل البوت")
    ck.ok("other-maker.example" in done, "تنبيه: البوت كان مربوطاً بخدمة أخرى")
    panel = [b for c in tg.out(MID) if "بوتك أصبح حياً" in c["p"].get("text", "") for row in c["p"]["reply_markup"]["inline_keyboard"] for b in row]
    ck.ok(any(b.get("url", "").endswith("?start=panel") for b in panel), "زر يفتح غرفة التحكم مباشرة")
    ck.ok(any(c["method"] == "deleteMessage" for c in tg.calls if c["bot"] == MID), "حذف رسالة التوكن")
    ck.ok(any("بوت جديد" in c["p"].get("text", "") and str(c["p"].get("chat_id")) == str(ADMIN) for c in tg.out(MID)), "إشعار المدير")

    print("— الصانع: بوتاتي ولوحتي —")
    t = await tg.click(MAKER, ali, "m:home")
    ck.ok("بوتاتك: <b>1</b>" in t and "مستواك" in t, "الرئيسية تتحول إلى ملخص")
    t = await tg.click(MAKER, ali, "m:bots")
    ck.ok("1 تعمل" in t and tg.find(MID, f"@b{B1}_bot"), "بوتاتي")
    t = await tg.press(MAKER, ali, f"@b{B1}_bot")
    ck.ok("الأعضاء" in t and "▁" in t and tg.find(MID, "غرفة التحكم")["url"].endswith("start=panel"), "بطاقة البوت")
    ck.ok("كل الأعضاء" in await tg.press(MAKER, ali, "الإحصائيات"), "إحصائيات البوت من الصانع")
    ck.ok("يعمل ويستقبل" in await tg.click(MAKER, ali, f"m:chk:{B1}"), "فحص البوت")
    t = await tg.click(MAKER, ali, f"m:dis:{B1}")
    ck.ok("متوقف مؤقتاً" in t and not mgr.running(B1), "إيقاف مؤقت")
    t = await tg.click(MAKER, ali, f"m:en:{B1}")
    ck.ok("🟢 يعمل" in t and mgr.running(B1), "تشغيل")
    t = await tg.click(MAKER, ali, "m:stats")
    ck.ok("لوحتك" in t and "أفضل بوتاتك" in t and "حسب النوع" in t, "لوحتي")
    ck.ok("start=ref_500" in await tg.click(MAKER, ali, "m:ref"), "رابط الدعوة")
    await tg.click(MAKER, ali, "m:setlang:en")
    ck.ok("Your bots" in tg.text(MID), "اللغة الإنجليزية")
    await tg.click(MAKER, ali, "m:setlang:ar")
    ck.ok("أين لوحة تحكم بوتي" in await tg.click(MAKER, ali, "m:faq"), "الأسئلة الشائعة")
    await tg.click(MAKER, ali, "m:bug")
    ck.ok("وصل بلاغك" in await tg.say(MAKER, ali, "الزر لا يعمل"), "البلاغ")
    await tg.say(MAKER, sara, "/start ref_500")
    ck.ok("دخلوا عبرك: <b>1</b>" in await tg.click(MAKER, ali, "m:ref"), "عدّ الدعوات")
    ck.ok("بوتاتك" in await tg.click(MAKER, sara, f"m:b:{B1}") and "(0)" in tg.text(MID), "لا يصل مستخدم لبوت غيره")

    print("— لوحة الإدارة —")
    t = await tg.say(MAKER, boss, "/start")
    ck.ok(tg.find(MID, "لوحة الإدارة"), "زر لوحة الإدارة يظهر للمدير")
    t = await tg.press(MAKER, boss, "لوحة الإدارة")
    ck.ok("مستخدمو الصانع" in t and "البوتات" in t and ("▁" in t or "█" in t), "نظرة عامة للمدير")
    n0 = len(tg.out(MID))
    await tg.click(MAKER, sara, "m:adm:home")
    ck.ok(not any("لوحة الإدارة</b>" in x for x in outs()[n0:]), "غير المدير لا يفتح لوحة الإدارة")
    t = await tg.click(MAKER, boss, "m:adm:u")
    ck.ok("مستخدمو الصانع" in t and tg.find(MID, "Sara"), "قائمة المستخدمين")
    await tg.click(MAKER, boss, "m:adm:us")
    t = await tg.say(MAKER, boss, "@sara_s")
    ck.ok("Sara" in t and "600" in t, "بحث عن مستخدم بالمعرّف")
    await tg.click(MAKER, boss, "m:adm:ub:600")
    n0 = len(tg.out(MID))
    await tg.say(MAKER, sara, "/start")
    ck.ok(any("إيقاف حسابك" in x for x in outs()[n0:]) and not any("أهلاً Sara" in x for x in outs()[n0:]), "المحظور لا يستخدم الصانع")
    await tg.click(MAKER, boss, "m:adm:ub:600")
    ck.ok("أهلاً Sara" in await tg.say(MAKER, sara, "/start"), "رفع الحظر")
    t = await tg.click(MAKER, boss, "m:adm:b:0")
    ck.ok(tg.find(MID, f"@b{B1}_bot"), "قائمة كل البوتات")
    t = await tg.click(MAKER, boss, f"m:adm:bc:{B1}")
    ck.ok("صانع البوت" in t and "500" in t and "تاريخ الإنشاء" in t and "إجمالي المستخدمين" in t, "بطاقة بوت للمدير")
    await tg.click(MAKER, boss, f"m:adm:bt:{B1}")
    ck.ok(not mgr.running(B1), "المدير يوقف بوتاً")
    await tg.click(MAKER, boss, f"m:adm:bt:{B1}")
    ck.ok(mgr.running(B1), "المدير يشغّل بوتاً")
    await tg.click(MAKER, boss, "m:adm:tt:xo")
    await tg.click(MAKER, sara, "m:all:0")
    ck.ok("33" in tg.text(MID), "تعطيل نوع يخفيه من القائمة")
    await tg.click(MAKER, boss, "m:adm:tt:xo")
    await tg.click(MAKER, boss, "m:adm:sm")
    n0 = len(tg.calls)
    await tg.click(MAKER, sara, "m:new")
    ck.ok(any("صيانة" in str(c["p"].get("text")) for c in tg.calls[n0:]), "وضع الصيانة يوقف غير المدير")
    await tg.click(MAKER, boss, "m:adm:sm")
    await tg.click(MAKER, boss, "m:adm:sl")
    await tg.say(MAKER, boss, "1")
    await tg.click(MAKER, ali, "m:tpl:xo")
    lim = await tg.say(MAKER, ali, tok(200000299))
    ck.ok("للحد الأقصى" in lim, "حد البوتات لكل مستخدم")
    await tg.click(MAKER, boss, "m:adm:sl")
    await tg.say(MAKER, boss, "0")
    tg.chats["@makerchan"] = {"id": -1021, "type": "channel", "title": "قناة الصانع", "username": "makerchan"}
    tg.members[(-1021, MID)] = "administrator"
    await tg.click(MAKER, boss, "m:adm:fsa")
    ck.ok("أضيفت" in await tg.say(MAKER, boss, "@makerchan"), "اشتراك إجباري للصانع")
    n0 = len(tg.out(MID))
    await tg.click(MAKER, sara, "m:new")
    ck.ok(any("اشترك في قناتنا" in x for x in outs()[n0:]), "غير المشترك يُطلب منه الاشتراك")
    tg.members[(-1021, 600)] = "member"
    ck.ok("الخطوة 1" in await tg.click(MAKER, sara, "m:new"), "المشترك يدخل")
    await tg.click(MAKER, boss, "m:adm:fsd:0")
    await tg.click(MAKER, boss, "m:adm:bcu")
    await tg.say(MAKER, boss, "تحديث جديد!")
    await tg.press(MAKER, boss, "إرسال")
    await asyncio.sleep(0.6)
    await tg.settle()
    ck.ok(sum(1 for c in tg.calls if c["bot"] == MID and c["method"] == "copyMessage") >= 3 and "انتهت الإذاعة" in tg.text(MID), "إذاعة لمستخدمي الصانع")
    ck.ok("البلاغات" in await tg.click(MAKER, boss, "m:adm:rep") and "الزر لا يعمل" in tg.text(MID), "قائمة البلاغات")
    ck.ok("الأخطاء" in await tg.click(MAKER, boss, "m:adm:err"), "قائمة الأخطاء")
    ck.ok("حد البوتات" in await tg.click(MAKER, boss, "m:adm:s"), "إعدادات المنصة")

    print("— البوت المصنوع: غرفة التحكم —")
    T = tok(B1)
    t = await tg.say(T, ali, "/start panel")
    ck.ok("غرفة التحكم" in t and "الزخرفة" in t and "▁" in t, "غرفة التحكم تظهر للمالك")
    n0 = len(tg.out(B1))
    await tg.say(T, sara, "/start")
    new = outs(B1)[n0:]
    ck.ok(any("أرسل اسمك" in x for x in new), "واجهة العضو")
    foot = [c for c in tg.out(B1)[n0:] if "عجبك البوت" in c["p"].get("text", "") and f"@b{MID}_bot" in c["p"]["text"]]
    ck.ok(len(foot) == 1 and foot[0]["p"]["reply_markup"]["inline_keyboard"][0][0]["url"].endswith("start=ref_500"), "دعوة «اصنع بوتك» للعضو الجديد برابط المالك")
    n0 = len(tg.out(B1))
    await tg.say(T, sara, "/start")
    ck.ok(not any("عجبك البوت" in x for x in outs(B1)[n0:]), "الدعوة لا تتكرر لنفس العضو في اليوم نفسه")
    ck.ok("𝗦𝗮𝗿𝗮" in await tg.say(T, sara, "Sara"), "القالب يعمل")
    await tg.click(T, sara, "o:g:aud")
    ck.ok(any(c["method"] == "answerCallbackQuery" and "للمالك" in str(c["p"].get("text")) for c in tg.calls), "منع غير المالك من اللوحة")
    for g, needle in [("aud", "الجمهور"), ("gate", "الدخول والترحيب"), ("auto", "الردود الآلية"), ("sys", "النظام")]:
        ck.ok(needle in await tg.click(T, ali, f"o:g:{g}"), f"قسم {g}")
    for scr, needle in [("stats", "كل الأعضاء"), ("users", "الأكثر تفاعلاً"), ("bc", "لمن تريد"), ("fs", "الاشتراك الإجباري"),
                        ("sl", "روابط التتبّع"), ("ban", "قائمة الحظر"), ("wel", "رسالة الترحيب"), ("qr", "ردود بالكلمات"),
                        ("sc", "أوامر مختصرة"), ("ad", "تنظيف تلقائي"), ("guide", "دليل"), ("set", "قفل المحتوى"), ("sys", "النسخ"), ("adm", "المشرفون")]:
        ck.ok(needle in await tg.click(T, ali, f"o:{scr}"), f"شاشة {scr}")
    await tg.click(T, ali, "o:qr")
    ck.ok(tg.find(B1, "رجوع")["callback_data"] == "o:g:auto", "زر الرجوع يعود إلى قسمه")

    await tg.click(T, ali, "o:qradd")
    await tg.say(T, ali, "السعر")
    await tg.say(T, ali, "السعر 5$")
    ck.ok(await tg.say(T, sara, "السعر") == "السعر 5$", "رد بالكلمة")
    await tg.click(T, ali, "o:scadd")
    await tg.say(T, ali, "price")
    await tg.say(T, ali, "قائمة الأسعار")
    ck.ok(await tg.say(T, sara, "/price") == "قائمة الأسعار", "أمر مختصر")
    await tg.click(T, ali, "o:welset")
    await tg.say(T, ali, "مرحباً {name}")
    await tg.click(T, ali, "o:welbtn")
    await tg.say(T, ali, "قناتنا - https://t.me/x && موقعنا - https://x.com")
    n0 = len(tg.out(B1))
    await tg.say(T, sara, "/start")
    new = tg.out(B1)[n0:]
    wel = next((c for c in new if "مرحباً Sara" in c["p"]["text"]), None)
    ck.ok(wel is not None and len(wel["p"]["reply_markup"]["inline_keyboard"][0]) == 2, "رسالة الترحيب بأزرارها")
    await tg.click(T, ali, "o:sladd")
    t = await tg.say(T, ali, "إعلان")
    code = t.split("start=sl_")[1].split("<")[0]
    await tg.say(T, omar, f"/start sl_{code}")
    ck.ok("إعلان</b> — 1" in await tg.click(T, ali, "o:sl"), "عدّاد رابط التتبّع")
    await tg.click(T, ali, "o:banadd")
    await tg.say(T, ali, "700")
    n0 = len(tg.out(B1))
    await tg.say(T, omar, "hello")
    ck.ok(len(tg.out(B1)) == n0, "المحظور لا يُرَد عليه")
    tg.chats["@chan"] = {"id": -1005, "type": "channel", "title": "قناتي", "username": "chan"}
    tg.members[(-1005, B1)] = "administrator"
    await tg.click(T, ali, "o:fsadd")
    ck.ok("المصادر: 1" in await tg.say(T, ali, "@chan"), "إضافة قناة اشتراك إجباري")
    t = await tg.say(T, sara, "Sara")
    ck.ok("اشترك أولاً" in t and tg.find(B1, "قناتي")["url"] == "https://t.me/chan", "حجب غير المشترك")
    tg.members[(-1005, 600)] = "member"
    await tg.press(T, sara, "تحقّقت")
    ck.ok("أرسل اسمك" in tg.text(B1) or "مرحباً" in tg.text(B1), "السماح بعد الاشتراك")
    await tg.click(T, ali, "o:bca:pv")
    await tg.say(T, ali, "عرض جديد")
    await tg.press(T, ali, "إرسال")
    await asyncio.sleep(0.5)
    await tg.settle()
    ck.ok(len([c for c in tg.calls if c["bot"] == B1 and c["method"] == "copyMessage"]) >= 3 and "انتهت الإذاعة" in tg.text(B1), "رسالة جماعية")
    await tg.click(T, ali, "o:syssave")
    await tg.click(T, ali, "o:qrdel:0")
    ck.ok("العدد: 0" in await tg.click(T, ali, "o:qr"), "حذف رد")
    await tg.click(T, ali, "o:syslist")
    await tg.press(T, ali, "♻️")
    ck.ok("العدد: 1" in await tg.click(T, ali, "o:qr"), "استرجاع النسخة")
    await tg.click(T, ali, "o:sysexp")
    ck.ok(any(c["method"] == "sendDocument" and c["bot"] == B1 for c in tg.calls), "تصدير ملف النسخة")
    await tg.click(T, ali, "o:tg:protect")
    await tg.say(T, sara, "X")
    ck.ok(tg.last(B1).get("protect_content") in (True, "true", "True"), "قفل المحتوى")
    ck.ok(any(c["method"] == "setMyCommands" and c["bot"] == B1 for c in tg.calls), "قائمة أوامر البوت")

    print("— تعارض التوكن ومعالجة الأخطاء —")
    import time
    from telegram.error import Conflict
    await mgr._conflict(B1)
    mgr.conflicts[B1]["first"] = time.time() - 60
    n0 = len(tg.out(MID))
    await mgr._conflict(B1)
    ck.ok(mgr.running(B1) and mgr.in_conflict(B1), "التعارض لا يوقف البوت")
    ck.ok(any("/revoke" in x for x in outs()[n0:]), "تنبيه المالك بحل التعارض")
    ck.ok("مستخدم في مكان آخر" in await tg.click(MAKER, ali, f"m:b:{B1}"), "بطاقة البوت تعرض التعارض")
    mgr.conflicts.clear()
    assert Conflict
    from forge import child, errors
    orig = child.owner_home

    async def boom(c):
        raise RuntimeError("انفجار تجريبي")
    child.owner_home = boom
    n0 = len(tg.calls)
    await tg.say(T, ali, "/admin")
    child.owner_home = orig
    new = tg.calls[n0:]
    ck.ok(any("خطأ غير متوقع" in str(c["p"].get("text")) and c["bot"] == B1 for c in new), "العضو يرى رسالة خطأ مهذبة بدل الصمت")
    ck.ok(any("خطأ تقني" in str(c["p"].get("text")) and str(c["p"].get("chat_id")) == str(ADMIN) for c in new), "المدير يُبلَّغ بالخطأ في تيليجرام")
    ck.ok(len(errors.RECENT) == 1 and "انفجار" in await tg.click(MAKER, boss, "m:adm:err"), "الخطأ يظهر في لوحة الإدارة")
    from harness import ERRORS
    ERRORS.clear()

    print("— إدارة متقدمة —")
    ck.ok("تغيير نوع" in await tg.click(MAKER, ali, f"m:chg:{B1}:0"), "قائمة تغيير النوع")
    await tg.click(MAKER, ali, f"m:trok:{B1}")
    code = tg.text(MID).split("start=tr_")[1].split("<")[0]
    await tg.say(MAKER, sara, f"/start tr_{code}")
    await tg.say(T, sara, "/start")
    ck.ok("غرفة التحكم" in tg.text(B1), "نقل الملكية: المالك الجديد يرى الغرفة")
    await tg.say(T, ali, "/start")
    ck.ok("غرفة التحكم" not in tg.text(B1), "نقل الملكية: القديم فقدها")
    n0 = len(tg.out(MID))
    await tg.say(MAKER, sara, f"/start tr_{code}")
    ck.ok(any("غير صالح" in x for x in outs()[n0:]), "رابط النقل لمرة واحدة")
    await tg.click(MAKER, sara, f"m:name:{B1}:ar")
    await tg.say(MAKER, sara, "بوت الزخرفة")
    ck.ok(any(c["method"] == "setMyName" and c["bot"] == B1 for c in tg.calls), "اسم البوت حسب اللغة")
    await tg.click(MAKER, sara, f"m:tok:{B1}")
    ck.ok("حُفظ التوكن" in await tg.say(MAKER, sara, tok(B1)) and mgr.running(B1), "تحديث التوكن")
    await tg.click(MAKER, sara, f"m:delok:{B1}")
    ck.ok(not mgr.running(B1) and "(0)" in tg.text(MID), "حذف البوت")

    ck.errors("كل السيناريوهات")
    ck.ok(not tg.problems, "كل الرسائل صالحة لتيليجرام (HTML، الطول، الأزرار)" + "".join("\n      " + p for p in sorted(set(tg.problems))[:12]))
    await mgr.shutdown()
    await tg.stop()
    ck.done()


asyncio.run(main())
