"""اختبار مزايا الإدارة: بطاقة البوت والتوكن، الإغلاق/الصيانة/المؤقت، الرسائل لأعضاء بوت، الترويج، وأدوات المالك."""
import asyncio
import datetime as dt
import time

from harness import ADMIN, MAKER, MID, Check, boot, make_bot, tok

B1, B2, SUB, SUBCHILD = 210000001, 210000002, 210000003, 210000004


async def main():  # noqa: C901
    tg, mgr = await boot()
    from forge import config, db
    from forge import plat as platform
    ck = Check()
    ali = tg.user(500, "Ali", username="ali_k")
    sara, omar, john = tg.user(600, "Sara", username="sara_s"), tg.user(700, "Omar"), tg.user(710, "John", lang="en")
    boss = tg.user(ADMIN, "Boss")
    T = tok(B1)

    def calls_since(n0, bot=None, method=None):
        return [c for c in tg.calls[n0:] if (bot is None or c["bot"] == bot) and (method is None or c["method"] == method)]

    def texts(n0, bot=None, to=None):
        return [str(c["p"].get("text", "")) for c in tg.calls[n0:] if (bot is None or c["bot"] == bot)
                and c["method"] in ("sendMessage", "editMessageText") and (to is None or str(c["p"].get("chat_id")) == str(to))]

    async def bg():
        await asyncio.sleep(0.5)
        await tg.settle()

    for u in (boss, ali, sara, omar):
        await tg.say(MAKER, u, "/start")
    await make_bot(tg, ali, B1, "decor")
    for u in (sara, omar, john):
        await tg.say(T, u, "/start")

    print("— بطاقة البوت وبياناته —")
    t = await tg.click(MAKER, boss, f"m:adm:bc:{B1}")
    ck.ok(f"@b{B1}_bot" in t and str(B1) in t and "تاريخ الإنشاء" in t and str(dt.datetime.now(dt.timezone.utc).year) in t, "البطاقة: يوزر البوت ورقمه وتاريخ إنشائه")
    ck.ok("إجمالي المستخدمين" in t and "<b>3" in t, "البطاقة: إجمالي المستخدمين")
    ck.ok("صانع البوت" in t and "Ali" in t and "@ali_k" in t and "<code>500</code>" in t, "البطاقة: اسم الصانع ويوزره وآيديه")
    ck.ok(tok(B1) not in t, "التوكن لا يظهر في البطاقة نفسها")
    n0 = len(tg.calls)
    await tg.press(MAKER, boss, "بيانات البوت والتوكن")
    sheet = next((x for x in texts(n0, MID, ADMIN) if "بيانات البوت" in x), "")
    ck.ok(tok(B1) in sheet and f"@b{B1}_bot" in sheet and "Ali" in sheet and "@ali_k" in sheet and "500" in sheet
          and "إجمالي المستخدمين" in sheet and "تاريخ الإنشاء" in sheet, "ورقة البيانات تجمع التوكن وكل بيانات البوت وصانعه")
    n0 = len(tg.calls)
    await tg.click(MAKER, boss, "m:adm:tkx")
    ck.ok(bool(calls_since(n0, MID, "deleteMessage")), "زر حذف رسالة التوكن")
    n0 = len(tg.calls)
    await tg.click(MAKER, sara, f"m:adm:tk:{B1}")
    await tg.click(MAKER, ali, f"m:adm:tk:{B1}")
    ck.ok(not any(tok(B1) in x for x in texts(n0)), "غير المدير لا يرى التوكن")
    ck.ok("عرض التوكن" in await tg.click(MAKER, boss, "m:adm:log"), "عرض التوكن يُسجَّل في سجل الإدارة")

    print("— إغلاق بسبب مخالفة مع إبلاغ الأعضاء —")
    await tg.click(MAKER, boss, f"m:adm:bc:{B1}")
    t = await tg.press(MAKER, boss, "🔒 إغلاق")
    ck.ok("اختر السبب" in t and tg.find(MID, "مخالفة الشروط والأحكام"), "قائمة أسباب الإغلاق")
    t = await tg.press(MAKER, boss, "مخالفة الشروط والأحكام")
    ck.ok("أبلغ الأعضاء (3)" in str(tg.buttons(MID)) and "مخالفة الشروط" in t, "تأكيد الإغلاق يعرض عدد الأعضاء")
    n0 = len(tg.calls)
    await tg.press(MAKER, boss, "نفّذ وأبلغ الأعضاء")
    await bg()
    got = {str(c["p"]["chat_id"]) for c in calls_since(n0, B1, "sendMessage") if "مغلق" in c["p"]["text"] or "closed" in c["p"]["text"]}
    ck.ok(got == {"600", "700", "710"}, "إشعار الإغلاق وصل كل الأعضاء عبر البوت نفسه")
    ck.ok(any("violation of the terms" in c["p"]["text"].lower() for c in calls_since(n0, B1, "sendMessage") if str(c["p"]["chat_id"]) == "710"), "العضو الإنجليزي يستلم الإشعار بلغته")
    ck.ok(any("إشعار من إدارة المنصة" in x and "مخالفة الشروط والأحكام" in x for x in texts(n0, MID, 500)), "المالك يُبلَّغ بالسبب عبر الصانع")
    ck.ok(any("انتهى الإرسال" in x and "وصلت: 3" in x for x in texts(n0, MID, ADMIN)), "تقرير الإرسال يصل المدير")
    ck.ok(mgr.running(B1), "البوت المغلق يبقى مشغّلاً ليعرض الإشعار")
    t = await tg.say(T, sara, "/start")
    ck.ok("هذا البوت مغلق" in t and "مخالفة الشروط والأحكام" in t, "العضو يرى إشعار الإغلاق بدل البوت")
    n0 = len(tg.calls)
    await tg.click(T, omar, "t:home")
    ck.ok(any("مغلق" in str(c["p"].get("text")) and c["p"].get("show_alert") for c in calls_since(n0, B1, "answerCallbackQuery")), "الأزرار ترد بتنبيه الإغلاق")
    t = await tg.say(T, ali, "/admin")
    ck.ok("هذا البوت مغلق" in t and "طلب مراجعة" in t and "غرفة التحكم" not in t, "المالك نفسه لا يدخل البوت المغلق")
    t = await tg.click(MAKER, ali, f"m:b:{B1}")
    ck.ok("مغلق من الإدارة" in t and "مخالفة الشروط" in t and tg.find(MID, "طلب مراجعة"), "بطاقة المالك تعرض الإغلاق والسبب وزر المراجعة")
    await tg.click(MAKER, ali, f"m:delok:{B1}")
    await tg.click(MAKER, ali, f"m:tok:{B1}")
    ck.ok(mgr.running(B1) and "مغلق من الإدارة" in tg.text(MID), "المالك لا يحذف البوت المغلق ولا يغيّر توكنه")
    t = await tg.click(MAKER, boss, "m:adm:b:0:lock")
    ck.ok("مغلقة" in t and tg.find(MID, f"🔒 @b{B1}_bot"), "فلتر «المغلقة» في قائمة البوتات")
    ck.ok("مغلقة من الإدارة: <b>1" in await tg.click(MAKER, boss, "m:adm:home"), "لوحة الإدارة تعدّ البوتات المغلقة")

    print("— طلب المراجعة وإعادة الفتح —")
    await tg.click(MAKER, ali, f"m:apl:{B1}")
    n0 = len(tg.calls)
    t = await tg.say(MAKER, ali, "حذفت المحتوى المخالف")
    ck.ok("وصل طلبك" in t and any("طلب مراجعة" in x and "حذفت المحتوى" in x for x in texts(n0, MID, ADMIN)), "طلب المراجعة يصل المدير")
    n0 = len(tg.calls)
    await tg.click(MAKER, ali, f"m:apl:{B1}")
    ck.ok(any("قيد المراجعة" in str(c["p"].get("text")) for c in calls_since(n0, MID, "answerCallbackQuery")), "لا يتكرر طلب المراجعة قبل 6 ساعات")
    t = await tg.click(MAKER, boss, "m:adm:rep")
    ck.ok("📨" in t and tg.find(MID, f"@b{B1}_bot"), "طلب المراجعة في البلاغات مع زر بطاقة البوت")
    await tg.click(MAKER, boss, f"m:adm:ul:{B1}")
    n0 = len(tg.calls)
    await tg.press(MAKER, boss, "افتح وأبلغ الأعضاء")
    await bg()
    ck.ok(sum(1 for c in calls_since(n0, B1, "sendMessage") if "عاد البوت" in c["p"]["text"] or "is back" in c["p"]["text"]) == 3, "إشعار إعادة الفتح يصل الأعضاء")
    ck.ok(any("فتح بوتك" in x for x in texts(n0, MID, 500)), "المالك يُبلَّغ بإعادة الفتح")
    ck.ok("أرسل اسمك" in await tg.say(T, sara, "/start"), "البوت يعود للعمل بعد الفتح")

    print("— إغلاق مؤقت —")
    await tg.click(MAKER, boss, f"m:adm:lk:{B1}:t")
    ck.ok(tg.find(MID, "3 أيام") and tg.find(MID, "مدة أخرى"), "اختيار مدة الإغلاق المؤقت")
    await tg.click(MAKER, boss, f"m:adm:lkd:{B1}:x")
    await tg.say(MAKER, boss, "12")
    await tg.click(MAKER, boss, f"m:adm:lkr:{B1}:x")
    t = await tg.say(MAKER, boss, "إزعاج المستخدمين")
    ck.ok("12 س" in t and "إزعاج المستخدمين" in t, "مدة وسبب مخصصان")
    await tg.press(MAKER, boss, "نفّذ دون إبلاغ")
    t = await tg.say(T, sara, "/start")
    ck.ok("مغلق مؤقتاً" in t and "يعود للعمل بعد" in t and "إزعاج المستخدمين" in t, "العضو يرى الإغلاق المؤقت والمدة المتبقية")
    ck.ok("يُفتح تلقائياً" in await tg.click(MAKER, boss, f"m:adm:bc:{B1}"), "بطاقة المدير تعرض موعد الفتح")
    (await platform.adm(B1))["lock"]["until"] = time.time() - 1
    n0 = len(tg.calls)
    await mgr.tick()
    ck.ok(platform.lock_of(await platform.adm(B1)) is None and any("انتهت مدة الإغلاق" in x for x in texts(n0, MID, 500)), "الإغلاق المؤقت ينتهي تلقائياً ويُبلَّغ المالك")
    ck.ok("أرسل اسمك" in await tg.say(T, sara, "/start"), "البوت يعود للعمل تلقائياً")

    print("— وضع الصيانة —")
    await tg.click(MAKER, boss, f"m:adm:lk:{B1}:m")
    await tg.press(MAKER, boss, "نفّذ دون إبلاغ")
    ck.ok("في صيانة" in await tg.say(T, sara, "/start"), "صيانة الإدارة: العضو يرى رسالة الصيانة")
    t = await tg.say(T, ali, "/admin")
    ck.ok("غرفة التحكم" in t and "صيانة" in t, "صيانة الإدارة: المالك يدخل غرفة التحكم ويرى التنبيه")
    await tg.click(MAKER, boss, f"m:adm:ulgo:{B1}:0")
    await tg.click(T, ali, "o:set")
    ck.ok(tg.find(B1, "وضع الصيانة"), "خيار الصيانة في غرفة تحكم المالك")
    await tg.click(T, ali, "o:mt")
    ck.ok("البوت في صيانة" in await tg.say(T, sara, "/start"), "صيانة المالك: الرسالة الافتراضية")
    await tg.click(T, ali, "o:mttxt")
    await tg.say(T, ali, "نعود غداً بإذن الله")
    ck.ok("نعود غداً" in await tg.say(T, sara, "hello"), "صيانة المالك: رسالة مخصصة")
    ck.ok("وضع الصيانة مفعّل" in await tg.say(T, ali, "/admin"), "المالك يرى تنبيه الصيانة في غرفته")
    await tg.click(T, ali, "o:mt")
    ck.ok("أرسل اسمك" in await tg.say(T, sara, "/start"), "إيقاف صيانة المالك")

    print("— رسالة لأعضاء بوت وتحذير المالك —")
    t = await tg.click(MAKER, boss, f"m:adm:bm:{B1}")
    ck.ok("رسالة لأعضاء" in t and tg.find(MID, "أُغلق بسبب مخالفة"), "قائمة الإشعارات الجاهزة")
    t = await tg.click(MAKER, boss, f"m:adm:bmp:{B1}:0")
    ck.ok("معاينة" in t and "مخالفة الشروط والأحكام" in t, "معاينة الإشعار الجاهز")
    n0 = len(tg.calls)
    await tg.press(MAKER, boss, "إرسال")
    await bg()
    ck.ok(sum(1 for c in calls_since(n0, B1, "sendMessage") if "إشعار من إدارة المنصة" in c["p"]["text"] or "Notice from the platform" in c["p"]["text"]) == 4, "الإشعار الجاهز يصل كل الأعضاء (والمالك منهم)")
    await tg.click(MAKER, boss, f"m:adm:bmc:{B1}")
    await tg.say(MAKER, boss, "تنبيه خاص من الإدارة")
    n0 = len(tg.calls)
    await tg.press(MAKER, boss, "إرسال")
    await bg()
    ck.ok(sum(1 for c in calls_since(n0, B1, "sendMessage") if "تنبيه خاص من الإدارة" in c["p"]["text"]) == 4, "الرسالة المخصصة تصل كل الأعضاء")
    await tg.click(MAKER, boss, f"m:adm:wn:{B1}")
    n0 = len(tg.calls)
    t = await tg.say(MAKER, boss, "أزل الروابط المخالفة خلال 24 ساعة")
    ck.ok("وصل التحذير" in t and any("تحذير من إدارة المنصة" in x and "أزل الروابط" in x for x in texts(n0, MID, 500)), "تحذير المالك")
    ck.ok("تحذيرات سابقة للمالك: 1" in await tg.click(MAKER, boss, f"m:adm:bc:{B1}"), "التحذير يُحفظ في البطاقة")

    print("— رسالة الترويج —")
    t = await tg.click(MAKER, boss, "m:adm:pm")
    ck.ok("رسالة الترويج" in t and "عجبك البوت" in t and "تظهر في كل البوتات" in t, "شاشة رسالة الترويج")
    n0 = len(tg.calls)
    await tg.say(T, tg.user(801, "N1"), "/start")
    pr = [c for c in calls_since(n0, B1, "sendMessage") if "عجبك البوت" in c["p"]["text"]]
    ck.ok(len(pr) == 1 and f"@b{MID}_bot" in pr[0]["p"]["text"] and pr[0]["p"]["reply_markup"]["inline_keyboard"][0][0]["url"].endswith("start=ref_500"), "الترويج الافتراضي مع رسالة البداية")
    await tg.click(MAKER, boss, f"m:adm:pr:{B1}")
    t = await tg.click(MAKER, boss, f"m:adm:pr:{B1}")
    ck.ok("معطّلة لهذا البوت" in t, "تعطيل الترويج لبوت بعينه")
    n0 = len(tg.calls)
    await tg.say(T, tg.user(802, "N2"), "/start")
    ck.ok(not any("عجبك البوت" in x for x in texts(n0, B1)), "البوت المستثنى لا يرسل الترويج")
    await tg.click(MAKER, boss, f"m:adm:pr:{B1}")          # تلقائي
    await tg.click(MAKER, boss, "m:adm:pmt")                # الوضع العام متوقف
    n0 = len(tg.calls)
    await tg.say(T, tg.user(803, "N3"), "/start")
    ck.ok(not any("عجبك البوت" in x for x in texts(n0, B1)), "إيقاف الوضع العام يوقف الترويج")
    await tg.click(MAKER, boss, f"m:adm:pr:{B1}")          # مفعّل دائماً
    t = await tg.click(MAKER, boss, "m:adm:pml")
    ck.ok(tg.find(MID, f"🟢 @b{B1}_bot"), "قائمة البوتات المحددة")
    await tg.click(MAKER, boss, "m:adm:pmx")
    await tg.say(MAKER, boss, "مرحباً {name} 👋\nعجبك {bot}؟ اصنع مثله عند {maker}")
    n0 = len(tg.calls)
    await tg.say(T, tg.user(804, "Fatimi"), "/start")
    ck.ok(any("مرحباً Fatimi" in x and f"@b{B1}_bot" in x and f"@b{MID}_bot" in x for x in texts(n0, B1, 804)), "الترويج في البوت المختار فقط وبنص مخصص")
    n0 = len(tg.calls)
    await tg.click(MAKER, boss, "m:adm:pmv")
    ck.ok(any("مرحباً Boss" in x for x in texts(n0, MID, ADMIN)), "معاينة الترويج")
    await tg.click(MAKER, boss, f"m:adm:prt:{B1}")
    await tg.say(MAKER, boss, "نص خاص بهذا البوت {maker}")
    p = await platform.get(0)
    p["promo"].update(when="idle", idle=1, every=0)
    n0 = len(tg.calls)
    await tg.say(T, sara, "Sara")
    ck.ok(not any("نص خاص بهذا البوت" in x for x in texts(n0, B1, 600)), "وضع «بعد الاستخدام»: لا يُرسل أثناء الاستخدام")
    await asyncio.sleep(1.6)
    await tg.settle()
    ck.ok(any("نص خاص بهذا البوت" in x for x in texts(n0, B1, 600)), "وضع «بعد الاستخدام»: يُرسل بعد توقف العضو، وبالنص الخاص بالبوت")
    n0 = len(tg.calls)
    await tg.say(T, ali, "/admin")
    await asyncio.sleep(1.4)
    ck.ok(not any("نص خاص" in x for x in texts(n0, B1, 500)), "المالك لا يستلم الترويج")
    t = await tg.click(MAKER, boss, "m:adm:pmw")
    ck.ok("مع البداية وبعد انتهاء الاستخدام" in t, "تبديل وقت الإرسال")
    p["promo"].update(when="both", idle=120, every=86400, on=True, text="")
    await tg.click(MAKER, boss, f"m:adm:prt:{B1}")
    await tg.say(MAKER, boss, "0")
    await tg.click(MAKER, boss, "m:adm:pmr")
    await db.kv_set(999, "sys:platform", {"footer": False, "banned": [5]})
    old = await platform.get(999)
    ck.ok(old["promo"]["on"] is False and old["banned"] == [5] and (await platform.get(998))["banned"] == [], "ترقية إعداد النسخة السابقة وعزل الإعدادات")

    print("— توثيق، دخول غرفة التحكم، ملاحظة، نقل ملكية —")
    await tg.click(MAKER, boss, f"m:adm:vf:{B1}")
    ck.ok("موثّق" in await tg.click(MAKER, ali, f"m:b:{B1}"), "علامة التوثيق تظهر للمالك")
    await tg.say(T, boss, "/start")
    ck.ok("غرفة التحكم" not in tg.text(B1), "المدير عضو عادي في البوت افتراضياً")
    await tg.click(MAKER, boss, f"m:adm:sp:{B1}")
    ck.ok("غرفة التحكم" in await tg.say(T, boss, "/admin"), "المدير يدخل غرفة تحكم البوت بعد التفعيل")
    await tg.click(MAKER, boss, f"m:adm:sp:{B1}")
    await tg.click(MAKER, boss, f"m:adm:nt:{B1}")
    ck.ok("ملاحظتك" in await tg.say(MAKER, boss, "راقب هذا البوت"), "ملاحظة المدير")
    await tg.click(MAKER, boss, f"m:adm:to:{B1}")
    ck.ok("لم يفتح الصانع" in await tg.say(MAKER, boss, "12345"), "نقل الملكية يرفض مستخدماً مجهولاً")
    t = await tg.say(MAKER, boss, "600")
    ck.ok("Sara" in t, "تأكيد نقل الملكية")
    await tg.press(MAKER, boss, "انقل")
    ck.ok("غرفة التحكم" in await tg.say(T, sara, "/admin") and "(0)" in await tg.click(MAKER, ali, "m:bots"), "نقل الملكية من المدير")
    await tg.click(MAKER, boss, f"m:adm:togo:{B1}:500")
    await tg.click(MAKER, boss, f"m:adm:rs:{B1}")
    ck.ok(mgr.running(B1), "إعادة تشغيل البوت")

    print("— القوائم، البحث، التصدير، السجل —")
    await make_bot(tg, sara, B2, "xo")
    t = await tg.click(MAKER, boss, "m:adm:b:0:top")
    btns = [b["text"] for b in tg.buttons(MID) if "_bot" in b["text"]]
    ck.ok("مرتبة بعدد الأعضاء" in t and str(B1) in btns[0], "فلتر «الأكبر» يرتب بعدد الأعضاء")
    await tg.click(MAKER, boss, "m:adm:bs")
    ck.ok("صانع البوت" in await tg.say(MAKER, boss, "600") and f"@b{B2}_bot" in tg.text(MID), "البحث بآيدي الصانع يفتح بطاقة بوته")
    await tg.click(MAKER, boss, "m:adm:bs")
    ck.ok(f"@b{B1}_bot" in await tg.say(MAKER, boss, str(B1)), "البحث برقم البوت")
    t = await tg.click(MAKER, boss, "m:adm:top")
    ck.ok("أكبر البوتات" in t and "🥇" in t and "Ali" in t, "لوحة الأفضل")
    n0 = len(tg.calls)
    await tg.click(MAKER, boss, "m:adm:exp")
    doc = calls_since(n0, MID, "sendDocument")
    csv_text = tg.files.get("up/bots.csv", b"").decode("utf-8-sig")
    ck.ok(bool(doc) and "ali_k" in csv_text and str(B1) in csv_text and tok(B1) not in csv_text, "تصدير قائمة البوتات بلا توكنات")
    t = await tg.click(MAKER, boss, "m:adm:log")
    ck.ok(all(x in t for x in ("🔒 إغلاق", "🔓 فتح", "رسالة لأعضاء بوت", "تحذير مالك", "نقل ملكية")), "سجل الإدارة يوثّق الإجراءات")

    print("— المستخدم في لوحة الإدارة —")
    await tg.click(MAKER, boss, "m:adm:uxl:600")
    t = await tg.say(MAKER, boss, "1")
    ck.ok("خاص به" in t, "حد بوتات خاص بمستخدم")
    await tg.click(MAKER, sara, "m:tpl:xo")
    ck.ok("للحد الأقصى" in await tg.say(MAKER, sara, tok(210000099)), "الحد الخاص يُطبَّق")
    await tg.click(MAKER, boss, "m:adm:uxm:600")
    n0 = len(tg.calls)
    await tg.say(MAKER, boss, "أهلاً سارة")
    ck.ok(any("رسالة من إدارة المنصة" in x for x in texts(n0, MID, 600)) and bool(calls_since(n0, MID, "copyMessage")), "مراسلة مستخدم من الإدارة")
    await tg.click(MAKER, boss, "m:adm:uxck:600")
    ck.ok("هذا البوت مغلق" in await tg.say(tok(B2), omar, "/start"), "إغلاق كل بوتات مستخدم")
    await tg.click(MAKER, boss, "m:adm:uxo:600")
    await tg.say(tok(B2), omar, "/start")
    ck.ok("مغلق" not in tg.text(B2), "فتح كل بوتات مستخدم")
    t = await tg.click(MAKER, boss, "m:adm:s")
    ck.ok("التقرير اليومي" in t and "إشعاري بكل مستخدم جديد" in t, "إعدادات المنصة الجديدة")
    await tg.click(MAKER, boss, "m:adm:sn:user")
    n0 = len(tg.calls)
    await tg.say(MAKER, tg.user(900, "Newbie"), "/start")
    ck.ok(not any("مستخدم جديد" in x for x in texts(n0, MID, ADMIN)), "إيقاف إشعار المستخدم الجديد")
    await tg.click(MAKER, boss, "m:adm:sn:user")

    print("— التقرير اليومي —")
    await db.kv_set(0, "sys:lastreport", "2000-01-01")
    config.TZ_HOURS = 12 - dt.datetime.now(dt.timezone.utc).hour
    n0 = len(tg.calls)
    await mgr.tick()
    ck.ok(any("تقرير الأمس" in x and "بوتات جديدة" in x for x in texts(n0, MID, ADMIN)), "التقرير اليومي يصل المدير")
    n0 = len(tg.calls)
    await mgr.tick()
    ck.ok(not any("تقرير الأمس" in x for x in texts(n0, MID, ADMIN)), "التقرير مرة واحدة في اليوم")
    config.TZ_HOURS = 3

    print("— بلاغ من داخل البوت —")
    t = await tg.say(T, omar, "/report")
    ck.ok("الإبلاغ عن هذا البوت" in t, "أمر /report في البوت المصنوع")
    n0 = len(tg.calls)
    t = await tg.say(T, omar, "البوت يطلب كود تسجيل الدخول")
    rep = [c for c in calls_since(n0, MID, "sendMessage") if "بلاغ على بوت" in c["p"]["text"]]
    ck.ok("وصل بلاغك" in t and len(rep) == 1 and str(rep[0]["p"]["chat_id"]) == str(ADMIN)
          and rep[0]["p"]["reply_markup"]["inline_keyboard"][0][0]["callback_data"] == f"m:adm:bc:{B1}", "البلاغ يصل المدير مع زر بطاقة البوت")
    ck.ok("وصل بلاغك السابق" in await tg.say(T, omar, "/report"), "منع تكرار البلاغ")

    print("— أدوات المالك: الأعضاء —")
    t = await tg.click(T, ali, "o:users")
    ck.ok(tg.find(B1, "بحث عن عضو") and tg.find(B1, "تصدير الأعضاء"), "أدوات الأعضاء في غرفة التحكم")
    await tg.click(T, ali, "o:usearch")
    t = await tg.say(T, ali, "@sara_s")
    ck.ok("Sara" in t and "<code>600</code>" in t and "آخر نشاط" in t, "بطاقة العضو بالبحث")
    await tg.click(T, ali, "o:uban:600")
    n0 = len(tg.calls)
    await tg.say(T, sara, "/start")
    ck.ok(not texts(n0, B1, 600), "حظر عضو من بطاقته")
    await tg.click(T, ali, "o:uban:600")
    await tg.click(T, ali, "o:umsg:600")
    n0 = len(tg.calls)
    t = await tg.say(T, ali, "مرحباً سارة")
    ck.ok("وصلت رسالتك" in t and any(str(c["p"]["chat_id"]) == "600" for c in calls_since(n0, B1, "copyMessage")), "مراسلة عضو")
    n0 = len(tg.calls)
    await tg.click(T, ali, "o:uexp")
    members = tg.files.get(f"up/members_b{B1}_bot.csv", b"").decode("utf-8-sig")
    ck.ok(bool(calls_since(n0, B1, "sendDocument")) and "sara_s" in members and "600" in members, "تصدير أعضاء البوت")

    print("— صانع فرعي: لا توكنات لغير مدير المنصة —")
    await make_bot(tg, ali, SUB, "maker")
    await tg.say(tok(SUB), omar, "/start")
    await tg.click(tok(SUB), omar, "m:tpl:decor")
    await tg.say(tok(SUB), omar, tok(SUBCHILD))
    await tg.say(tok(SUB), ali, "/admin")
    t = await tg.click(tok(SUB), ali, f"m:adm:bc:{SUBCHILD}")
    ck.ok("صانع البوت" in t and "Omar" in t and not any("التوكن" in b["text"] or "غرفة التحكم" in b["text"] for b in tg.buttons(SUB)), "مدير الصانع الفرعي يرى البطاقة بلا زر التوكن")
    n0 = len(tg.calls)
    await tg.click(tok(SUB), ali, f"m:adm:tk:{SUBCHILD}")
    ck.ok(not any(tok(SUBCHILD) in x for x in texts(n0)), "مدير الصانع الفرعي لا يستخرج التوكن")
    await tg.click(tok(SUB), ali, f"m:adm:lk:{SUBCHILD}:m")
    await tg.click(tok(SUB), ali, f"m:adm:lkgo:{SUBCHILD}:0")
    ck.ok("في صيانة" in await tg.say(tok(SUBCHILD), sara, "/start"), "مدير الصانع الفرعي يضع بوتات صانعه في الصيانة")
    await tg.click(tok(SUB), ali, f"m:adm:ulgo:{SUBCHILD}:0")
    ck.ok("غير موجود" in await tg.click(tok(SUB), ali, f"m:adm:bc:{B1}"), "مدير الصانع الفرعي لا يصل إلى بوتات المنصة الرئيسية")
    await tg.click(tok(SUB), ali, f"m:adm:togo:{SUBCHILD}:500")
    await tg.say(tok(SUBCHILD), ali, "/admin")
    ck.ok("غرفة التحكم" not in tg.text(SUBCHILD), "مدير الصانع الفرعي لا ينقل بوتات مستخدميه إلى نفسه")
    t = await tg.click(MAKER, boss, f"m:adm:bc:{SUBCHILD}")
    ck.ok("أُنشئ عبر صانع فرعي" in t and f"@b{SUB}_bot" in t and "Omar" in t, "مدير المنصة يفتح بطاقة أي بوت حتى لو أُنشئ عبر صانع فرعي")
    await tg.click(MAKER, boss, "m:adm:b:0:sub")
    ck.ok(tg.find(MID, f"@b{SUBCHILD}_bot"), "فلتر «عبر صانع فرعي»")
    await tg.click(MAKER, boss, f"m:adm:lk:{SUB}:c")
    await tg.click(MAKER, boss, f"m:adm:lkr:{SUB}:0")
    await tg.click(MAKER, boss, f"m:adm:lkgo:{SUB}:0")
    ck.ok("هذا البوت مغلق" in await tg.say(tok(SUBCHILD), sara, "/start"), "إغلاق صانع فرعي يغلق البوتات المصنوعة عبره")
    t = await tg.click(MAKER, ali, "m:gbc")
    ck.ok("البوتات: 1" in t, "رسالة المالك لكل جمهوره تتخطى بوتاته المغلقة")
    await tg.click(MAKER, ali, "m:home")
    await tg.click(MAKER, boss, f"m:adm:ulgo:{SUB}:0")
    ck.ok("مغلق" not in await tg.say(tok(SUBCHILD), sara, "/start"), "فتح الصانع الفرعي يعيد بوتاته")

    print("— بوت كان المالك قد أوقفه —")
    await tg.click(MAKER, sara, f"m:dis:{B2}")
    await tg.click(MAKER, boss, f"m:adm:lk:{B2}:t")
    await tg.click(MAKER, boss, f"m:adm:lkd:{B2}:x")
    await tg.say(MAKER, boss, "0.0001")
    await tg.click(MAKER, boss, f"m:adm:lkr:{B2}:n")
    await tg.click(MAKER, boss, f"m:adm:lkgo:{B2}:0")
    lk = (await platform.adm(B2))["lock"]
    ck.ok(mgr.running(B2) and lk["until"] - time.time() > 50, "الإغلاق يشغّل البوت المتوقف ليعرض الإشعار، وأقل مدة دقيقة")
    ck.ok("مغلق مؤقتاً" in await tg.say(tok(B2), omar, "/start"), "إشعار الإغلاق المؤقت بمدة قصيرة")
    await tg.click(MAKER, boss, f"m:adm:ulgo:{B2}:0")
    ck.ok(not mgr.running(B2), "بعد الفتح يعود البوت متوقفاً كما تركه مالكه")
    await tg.click(MAKER, sara, f"m:en:{B2}")

    print("— حظر نهائي —")
    await tg.click(MAKER, boss, f"m:adm:bx:{B2}")
    n0 = len(tg.calls)
    await tg.press(MAKER, boss, "نعم، احظره")
    ck.ok(not mgr.running(B2) and B2 in (await platform.get(0))["blocked_bots"] and any("حظرت تسجيله" in x for x in texts(n0, MID, 600)), "الحظر النهائي يحذف البوت ويبلغ المالك")
    await tg.click(MAKER, boss, "m:adm:uxl:600")
    await tg.say(MAKER, boss, "-")
    await tg.click(MAKER, sara, "m:tpl:xo")
    ck.ok("محظور من المنصة" in await tg.say(MAKER, sara, tok(B2)) and not mgr.running(B2), "البوت المحظور لا يُسجَّل من جديد")
    await tg.say(tok(SUB), sara, "/start")
    await tg.click(tok(SUB), sara, "m:tpl:xo")
    ck.ok("محظور من المنصة" in await tg.say(tok(SUB), sara, tok(B2)) and not mgr.running(B2), "ولا يُسجَّل عبر صانع فرعي")
    t = await tg.click(MAKER, boss, "m:adm:bl")
    ck.ok(str(B2) in t, "قائمة البوتات المحظورة")
    await tg.click(MAKER, boss, f"m:adm:blx:{B2}")
    await tg.click(MAKER, sara, "m:tpl:xo")
    await tg.say(MAKER, sara, tok(B2))
    ck.ok(mgr.running(B2), "رفع الحظر يسمح بالتسجيل")

    print("— بعد إعادة التشغيل —")
    await tg.click(MAKER, boss, f"m:adm:lk:{B1}:c")
    await tg.click(MAKER, boss, f"m:adm:lkr:{B1}:2")
    await tg.click(MAKER, boss, f"m:adm:lkgo:{B1}:0")
    await mgr.shutdown()
    platform.reset_cache()
    await mgr.start_all()
    t = await tg.say(T, sara, "/start")
    ck.ok("هذا البوت مغلق" in t and "احتيال" in t, "الإغلاق يبقى بعد إعادة تشغيل السيرفر")
    await tg.click(MAKER, ali, "m:tpl:xo")
    ck.ok("مغلق من الإدارة" in await tg.say(MAKER, ali, tok(B1)), "إعادة إرسال التوكن لا تغيّر بوتاً مغلقاً")
    ck.ok("موثّق" not in t and (await platform.adm(B1))["verified"], "التوثيق والإعدادات محفوظة")

    ck.errors("كل السيناريوهات")
    ck.ok(not tg.problems, "كل الرسائل صالحة لتيليجرام (HTML، الطول، الأزرار)" + "".join("\n      " + p for p in sorted(set(tg.problems))[:12]))
    await mgr.shutdown()
    await tg.stop()
    ck.done()


asyncio.run(main())
